### ISSUE TITLE
Python 3.12 compatibility

### ISSUE THREAD

**Issue by bieniu** [pysnmp/pysnmp#56]
Is there a plan to make a package compatible with Python 3.12?

**Comment by lextm** [comment]
You might track https://github.com/lextudio/pysnmp/issues/10

**Comment by gpatel-fr** [comment]
Hello

stumbling on this issue, there could be an easy way to work around this by using the pyasyncore Pypi package. I don't use pysnmp myself so I did not try it out for you, sorry.

**Comment by lextm** [comment]
@gpatel-fr The question is whether people should rely on that package.

Nobody is actually maintaining that `pyasyncore` (except dumping the old files into it), so whatever bad happens the fire is on others, not you, right?

**Comment by gpatel-fr** [comment]
You could ask yourself another question: is answering like this to someone trying to help an efficient way of showing you as a thoroughly unpleasant character ?

**Comment by lextm** [comment]
@gpatel-fr You don't actually help, but copied some random information here. Don't overreact when people like me pointed out the fact that you don't like.
